<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Webbhuset\CollectorCheckout\ViewModel\CheckoutConfigProvider;

/**
 * @var Template $block
 * @var Escaper $escaper
 * @var CheckoutConfigProvider $viewModel 
 */
$viewModel = $block->getViewModel();
?>

<div id="block-summary" data-bind="scope:'block-summary'" class="content shipping-selector" data-role="content" aria-labelledby="block-shipping-heading">
    <h4 class="shipping-header"><?= __('Shipping Methods') ?></h4>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#block-summary": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /** @noEscape */ $viewModel->getSerializedCheckoutConfig() ?>;
        window.customerData = window.checkoutConfig.customerData;
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>");
            return url.setBaseUrl('<?= $escaper->escapeUrl($block->getBaseUrl()) ?>');
        })
    </script>
</div>
