<?php
/** @var \Webbhuset\CollectorCheckout\Block\Checkout $block */
/** @var \Magento\Framework\Escaper $escaper */

$viewModel = $block->getData('view_model');
/** @var \Webbhuset\CollectorCheckout\ViewModel\Iframe $viewModel */
$iframe = $viewModel->getIframe();
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "collectorIframe": {
                        "component": "collectorIframe",
                        "config":{
                            "src": "<?= $escaper->escapeUrl($viewModel->getIframeSrc()) ?>",
                            "dataToken": "<?= $escaper->escapeHtml($viewModel->getDataToken()) ?>",
                            "dataVersion": "<?= $escaper->escapeHtml($viewModel->getDataVersion()) ?>",
                            "dataLang": "<?= $escaper->escapeHtml($viewModel->getDataLang()) ?>",
                            "dataActionColor": "<?= $escaper->escapeHtml((string)$viewModel->getDataActionColor()) ?>",
                            "dataActionTextColor": "<?= $escaper->escapeHtml((string)$viewModel->getDataActionTextColor()) ?>"
                        }
                    }
                }
            }
        }
    }
</script>
<?php if ($iframe): ?>
    <div data-bind="scope: 'collectorIframe'" id="collectorIframe">
    </div>
<?php else: ?>
    <div id="collectorIframe">
        <?=__('The url is no longer valid')?>;
    </div>
<?php endif; ?>
