<?php

/**
 * @var Magento\Framework\View\Element\Template $block
 * @var \Webbhuset\CollectorCheckout\ViewModel\Success $successViewModel
 * @var \Webbhuset\CollectorCheckout\ViewModel\Iframe $iframeViewModel
 * @var Magento\Framework\Escaper $escaper
 */

$iframeViewModel = $block->getIframeViewModel();
$successViewModel = $block->getSuccessViewModel();
$iframe = $iframeViewModel->getIframe();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "collectorSuccess": {
                        "component": "collectorSuccess"
                    }
                }
            }
        }
    }
</script>

<?php if ($iframe): ?>
    <script>
        window.dataLayer = window.dataLayer || [];
        dataLayer.push(<?= /** @noEscape */ $successViewModel->getAnalyticsDatalayer() ?>);
        dataLayer.push(<?= /** @noEscape */ $successViewModel->getEnhancedEcommerceDatalayer() ?>);
    </script>
    <?= /** @noEscape */ $iframe ?>
<?php else: ?>
<div>
    <?= $escaper->escapeHtml(__('The url is no longer valid')) ?>
</div>
<?php endif; ?>
